name: Test

on: [push]

jobs:
  example:
    name: Run E2E tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Minikube resources
        uses: actions/cache@v3
        with:
          key: minikube
          path: |
            ~/.minikube/cache
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.28.0'
          kubernetes version: 'v1.25.4'
          github token: ${{ secrets.GITHUB_TOKEN }}
          driver: docker
      - name: Setup tests
        run: test/run.sh run
      - name: Check conditions
        run: test/check.sh
